// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using UnityEngine;
using System;

public class BasePage
{
	protected MainCamera camera;
	protected Rect messageRect = new Rect(64, 0, 640, 64);
	protected string message = "(no message)";
	
	protected Rect backButtonRect = new Rect(0, 0, 64, 64);

	protected GUIStyle buttonStyle = new GUIStyle();

	private bool buttonEnable = true;

	public BasePage (MainCamera camera)
	{
		this.camera = camera;
		this.buttonStyle.fontSize = 32;
	}

	protected void PerformBack()
	{
		camera.PopPage();
	}

	protected bool ButtonEnabled {
		set
		{
			buttonEnable = value;
		}
		get
		{
			return buttonEnable;
		}
	}

}

