// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using KiiCorp.Cloud.Storage;
using UnityEngine;
using System;

public class FindUserPage : BasePage, IPage
{
	// Find API
	private Rect usernameTextRect = new Rect(0, 128, 320, 64);
	private string username = "";
	private Rect findByUsernameButtonRect = new Rect(320, 128, 320, 64);

	private Rect emailTextRect = new Rect(0, 192, 320, 64);
	private string email = "";
	private Rect findByEmailButtonRect = new Rect(320, 192, 320, 64);

	private Rect phoneTextRect = new Rect(0, 256, 320, 64);
	private string phone = "";
	private Rect findByPhoneButtonRect = new Rect(320, 256, 320, 64);

	public FindUserPage (MainCamera camera) : base(camera)
	{
	}

	#region IPage implementation
	public void OnGUI ()
	{
		GUI.Label(messageRect, message);
		username = GUI.TextField(usernameTextRect, username);
		email = GUI.TextField(emailTextRect, email);
		phone = GUI.TextField(phoneTextRect, phone);

		GUI.enabled = ButtonEnabled;
		bool backClicked = GUI.Button(backButtonRect, "<");
		bool findByUsernameClicked = GUI.Button(findByUsernameButtonRect, "Find by Username");
		bool findByEmailClicked = GUI.Button(findByEmailButtonRect, "Find by Email");
		bool findByPhoneClicked = GUI.Button(findByPhoneButtonRect, "Find by Phone");
		GUI.enabled = true;
		
		if (backClicked)
		{
			PerformBack();
			return;
		}
		if (findByUsernameClicked)
		{
			PerformFindByUsername(username);
			return;
		}
		if (findByEmailClicked)
		{
			PerformFindByEmail(email);
			return;
		}
		if (findByPhoneClicked)
		{
			PerformFindByPhone(phone);
			return;
		}
	}

	void PerformFindByUsername (string username)
	{
		message = "Find user by username...";
		ButtonEnabled = false;
		
		KiiUser.FindUserByUserName(username, (KiiUser user, Exception e) =>
		                           {
			ButtonEnabled = true;
			if (e != null)
			{
				message = "Failed to find user " + e.ToString();
				return;
			}
			message = "User found " + user.Uri.ToString(); 
		});
	}
	
	void PerformFindByEmail (string email)
	{
		message = "Find user by email...";
		ButtonEnabled = false;
		
		KiiUser.FindUserByEmail(email, (KiiUser user, Exception e) =>
		                        {
			ButtonEnabled = true;
			if (e != null)
			{
				message = "Failed to find user " + e.ToString();
				return;
			}
			message = "User found " + user.Uri.ToString(); 
		});
	}
	
	void PerformFindByPhone (string phone)
	{
		message = "Find user by phone...";
		ButtonEnabled = false;
		
		KiiUser.FindUserByPhone(phone, (KiiUser user, Exception e) =>
		                        {
			ButtonEnabled = true;
			if (e != null)
			{
				message = "Failed to find user " + e.ToString();
				return;
			}
			message = "User found " + user.Uri.ToString(); 
		});
	}
	#endregion
}

